project:
  type: book
  output-dir: docs


book:
  title: "cluster-book"
  author: "Wojciech Bonna"
  date: "10/15/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - infrastructure.qmd
    - serwisy.qmd
    - framework.qmd
    - processing.qmd

format:
  html:
    theme:
      - cosmo
      - brand
